models:
  cart_balanced:
    family: CART
    class_weight: balanced

  random_forest_balanced:
    family: RandomForest
    n_estimators: 50
    class_weight: balanced_subsample

  xgboost_weighted:
    family: XGBoost
    n_estimators: 50
    max_depth: 4
    learning_rate: 0.1
    scale_pos_weight: auto

  lightgbm_unbalanced:
    family: LightGBM
    n_estimators: 50
    max_depth: -1
    learning_rate: 0.1
    objective: binary
    min_child_samples: 1
    min_data_in_leaf: 1
    is_unbalance: true
    verbose: -1

  lightgbm_weighted:
    family: LightGBM
    n_estimators: 50
    max_depth: -1
    learning_rate: 0.1
    objective: binary
    min_child_samples: 1
    min_data_in_leaf: 1
    scale_pos_weight: auto
    verbose: -1
